project:
  type: website

website:
  title: "website"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: [litera, custom_theme.scss]
    css: styles.css



